services:
  - type: web
    name: receipt-reward
    env: python
    pythonVersion: "3.9.0"  # Force Python 3.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rrs:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0